blank_issues_enabled: true
contact_links:
  - about: "Find detailed guides about common support issues in our forum"
    name: "ğŸ’¬ GitHub Discussions"
    url: "https://github.com/requestly/requestly/discussions"
  - about: "Ask a question on our forum"
    name: "â“ Question."
    url: "https://github.com/requestly/requestly/discussions"
  - about: "Get instant support from the Requestly Community Slack"
    name: "ğŸ‘‹ Slack"
    url: "https://bit.ly/requestly-slack"
