blank_issues_enabled: false
contact_links:
  - about: "Help us in creating Requestly's Roadmap by upvoting existing issues or feature requests"
    name: "â¬†ï¸ Upvote features you want to see next in Requestly"
    url: "https://github.com/requestly/requestly/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc"
  - about: "Ask a question on our forum"
    name: "â“ Question."
    url: "https://github.com/requestly/requestly/discussions"
  - about: "Get instant support from the Requestly Community Slack"
    name: "ğŸ‘‹ Slack"
    url: "https://bit.ly/requestly-slack"
